# Generated by Django 5.2.3 on 2025-06-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_provider_name', models.CharField(help_text='Name of the Cloud Service Provider', max_length=255)),
                ('data_center_location', models.CharField(max_length=255)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Submitted_by_CSP', 'Submitted by CSP'), ('Forwarded_to_STQC', 'Forwarded to STQC for Audit'), ('Audit_Completed_by_STQC', 'Audit Completed by STQC'), ('Approved_by_ScientistF', 'Approved by Scientist F'), ('Rejected_by_ScientistF', 'Rejected by Scientist F')], default='Submitted_by_CSP', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CSP_Submission', 'CSP Submission'), ('Audit_Report', 'Audit Report'), ('Other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='audit_documents/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
