# Generated by Django 5.2.3 on 2025-06-23 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrequest',
            name='csp',
            field=models.ForeignKey(limit_choices_to={'role': 'CSP'}, on_delete=django.db.models.deletion.CASCADE, related_name='audit_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='audit_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='audit_management.auditrequest'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remark',
            name='audit_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='audit_management.auditrequest'),
        ),
        migrations.AddField(
            model_name='remark',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
